#!/bin/bash

export DYLD_LIBRARY_PATH=/Users/mike/MJ2K

for psnr in 15 20 25 30 35 40; do
  for nlvl in nl vl; do
    ../read_j2k cat_hat_c1_psnr${psnr}_${nlvl}.j2k -l 1 cat_hat_c1_d1_psnr${psnr}_${nlvl}
    ../read_j2k cat_hat_c2_psnr${psnr}_${nlvl}.j2k -l 1 cat_hat_c2_d1_psnr${psnr}_${nlvl}
    ../read_j2k cat_hat_c2_psnr${psnr}_${nlvl}.j2k -l 2 cat_hat_c2_d2_psnr${psnr}_${nlvl}
  done
done

